### ISSUE TITLE
Food cannot be put into fridge and deep freezer

### ISSUE THREAD

**Issue by wormzjl** [DrFair/TFCEngineer#2]
They jumps back to player inventory when I tries to put them inside
Same thing happens if you tries to put tfc food in non-tfc containers, like the vanilla chest.
Probably some new check added in the latest version of tfc?

**Comment by DrFair** [comment]
Hey, since I am not able to replicate this with TFC Engineer v.1.1.1 and the latest TFC (v.0.79.29.922), can you please give me some more information about the pack you are running. It may be some other mod that is causing this issue.
The same goes with the other issue you opened (#3).

Thanks!

**Comment by wormzjl** [comment]
Ok this is really weird...

**Comment by wormzjl** [comment]
Seems that this is caused by the automated bellows addon, the fridge is not a TFC container actually?

container_handler {
    # Ejects all food fron non TFC containers on opening by a player. 'True' if enabled. [default: true]
    B:enabled=true
}

**Comment by DrFair** [comment]
Thank you for reporting this.
Should now be fixed in the latest release (v. 1.1.2)!

**Comment by wormzjl** [comment]
Thx!
